<?php
/**
 * TerminalLocation
 *
 * PHP version 5
 *
 * @category Class
 * @package  Gateway\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Delivery Gateway
 *
 * Delivery Gateway
 *
 * OpenAPI spec version: 2.16.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Gateway\Client\Model;

use \ArrayAccess;

/**
 * TerminalLocation Class Doc Comment
 *
 * @category    Class
 * @package     Gateway\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TerminalLocation implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'terminalLocation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'contact' => '\Gateway\Client\Model\Contact',
        'address_line1' => 'string',
        'address_line2' => 'string',
        'city' => 'string',
        'state' => 'string',
        'postal_code' => 'string',
        'country' => 'string',
        'notes' => 'string',
        'intention_transit_value' => 'string[]',
        'intention_transit_notes' => 'string',
        'intention_transfer_value' => 'string[]',
        'intention_transfer_notes' => 'string',
        'intention_arrangements_value' => 'string[]',
        'intention_arrangements_notes' => 'string',
        'intention_penetration_value' => 'string[]',
        'intention_penetration_notes' => 'string',
        'intention_services_value' => 'string[]',
        'intention_services_notes' => 'string',
        'intention_service_level_value' => 'string[]',
        'intention_service_level_notes' => 'string',
        'intention_notification_transports_value' => 'string[]',
        'intention_notification_transports_notes' => 'string',
        'intention_notification_types_value' => 'string[]',
        'intention_notification_types_notes' => 'string',
        'information_location_type_value' => 'string[]',
        'information_location_type_notes' => 'string',
        'information_venue_value' => 'string[]',
        'information_venue_notes' => 'string',
        'information_dock_value' => 'string[]',
        'information_dock_notes' => 'string',
        'information_obstacles_value' => 'string[]',
        'information_obstacles_notes' => 'string',
        'choices_transfer_value' => 'string[]',
        'choices_transfer_notes' => 'string',
        'plan_transit_value' => 'string[]',
        'plan_transit_notes' => 'string',
        'plan_transfer_value' => 'string[]',
        'plan_transfer_notes' => 'string',
        'plan_arrangements_value' => 'string[]',
        'plan_arrangements_notes' => 'string',
        'plan_penetration_value' => 'string[]',
        'plan_penetration_notes' => 'string',
        'plan_services_value' => 'string[]',
        'plan_services_notes' => 'string',
        'plan_service_level_value' => 'string[]',
        'plan_service_level_notes' => 'string',
        'plan_notification_transports_value' => 'string[]',
        'plan_notification_transports_notes' => 'string',
        'plan_notification_types_value' => 'string[]',
        'plan_notification_types_notes' => 'string',
        'accessorials_total' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'contact' => null,
        'address_line1' => null,
        'address_line2' => null,
        'city' => null,
        'state' => null,
        'postal_code' => null,
        'country' => null,
        'notes' => null,
        'intention_transit_value' => null,
        'intention_transit_notes' => null,
        'intention_transfer_value' => null,
        'intention_transfer_notes' => null,
        'intention_arrangements_value' => null,
        'intention_arrangements_notes' => null,
        'intention_penetration_value' => null,
        'intention_penetration_notes' => null,
        'intention_services_value' => null,
        'intention_services_notes' => null,
        'intention_service_level_value' => null,
        'intention_service_level_notes' => null,
        'intention_notification_transports_value' => null,
        'intention_notification_transports_notes' => null,
        'intention_notification_types_value' => null,
        'intention_notification_types_notes' => null,
        'information_location_type_value' => null,
        'information_location_type_notes' => null,
        'information_venue_value' => null,
        'information_venue_notes' => null,
        'information_dock_value' => null,
        'information_dock_notes' => null,
        'information_obstacles_value' => null,
        'information_obstacles_notes' => null,
        'choices_transfer_value' => null,
        'choices_transfer_notes' => null,
        'plan_transit_value' => null,
        'plan_transit_notes' => null,
        'plan_transfer_value' => null,
        'plan_transfer_notes' => null,
        'plan_arrangements_value' => null,
        'plan_arrangements_notes' => null,
        'plan_penetration_value' => null,
        'plan_penetration_notes' => null,
        'plan_services_value' => null,
        'plan_services_notes' => null,
        'plan_service_level_value' => null,
        'plan_service_level_notes' => null,
        'plan_notification_transports_value' => null,
        'plan_notification_transports_notes' => null,
        'plan_notification_types_value' => null,
        'plan_notification_types_notes' => null,
        'accessorials_total' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'contact' => 'contact',
        'address_line1' => 'addressLine1',
        'address_line2' => 'addressLine2',
        'city' => 'city',
        'state' => 'state',
        'postal_code' => 'postalCode',
        'country' => 'country',
        'notes' => 'notes',
        'intention_transit_value' => 'intention.transit.value',
        'intention_transit_notes' => 'intention.transit.notes',
        'intention_transfer_value' => 'intention.transfer.value',
        'intention_transfer_notes' => 'intention.transfer.notes',
        'intention_arrangements_value' => 'intention.arrangements.value',
        'intention_arrangements_notes' => 'intention.arrangements.notes',
        'intention_penetration_value' => 'intention.penetration.value',
        'intention_penetration_notes' => 'intention.penetration.notes',
        'intention_services_value' => 'intention.services.value',
        'intention_services_notes' => 'intention.services.notes',
        'intention_service_level_value' => 'intention.serviceLevel.value',
        'intention_service_level_notes' => 'intention.serviceLevel.notes',
        'intention_notification_transports_value' => 'intention.notificationTransports.value',
        'intention_notification_transports_notes' => 'intention.notificationTransports.notes',
        'intention_notification_types_value' => 'intention.notificationTypes.value',
        'intention_notification_types_notes' => 'intention.notificationTypes.notes',
        'information_location_type_value' => 'information.locationType.value',
        'information_location_type_notes' => 'information.locationType.notes',
        'information_venue_value' => 'information.venue.value',
        'information_venue_notes' => 'information.venue.notes',
        'information_dock_value' => 'information.dock.value',
        'information_dock_notes' => 'information.dock.notes',
        'information_obstacles_value' => 'information.obstacles.value',
        'information_obstacles_notes' => 'information.obstacles.notes',
        'choices_transfer_value' => 'choices.transfer.value',
        'choices_transfer_notes' => 'choices.transfer.notes',
        'plan_transit_value' => 'plan.transit.value',
        'plan_transit_notes' => 'plan.transit.notes',
        'plan_transfer_value' => 'plan.transfer.value',
        'plan_transfer_notes' => 'plan.transfer.notes',
        'plan_arrangements_value' => 'plan.arrangements.value',
        'plan_arrangements_notes' => 'plan.arrangements.notes',
        'plan_penetration_value' => 'plan.penetration.value',
        'plan_penetration_notes' => 'plan.penetration.notes',
        'plan_services_value' => 'plan.services.value',
        'plan_services_notes' => 'plan.services.notes',
        'plan_service_level_value' => 'plan.serviceLevel.value',
        'plan_service_level_notes' => 'plan.serviceLevel.notes',
        'plan_notification_transports_value' => 'plan.notificationTransports.value',
        'plan_notification_transports_notes' => 'plan.notificationTransports.notes',
        'plan_notification_types_value' => 'plan.notificationTypes.value',
        'plan_notification_types_notes' => 'plan.notificationTypes.notes',
        'accessorials_total' => 'accessorials.total'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'contact' => 'setContact',
        'address_line1' => 'setAddressLine1',
        'address_line2' => 'setAddressLine2',
        'city' => 'setCity',
        'state' => 'setState',
        'postal_code' => 'setPostalCode',
        'country' => 'setCountry',
        'notes' => 'setNotes',
        'intention_transit_value' => 'setIntentionTransitValue',
        'intention_transit_notes' => 'setIntentionTransitNotes',
        'intention_transfer_value' => 'setIntentionTransferValue',
        'intention_transfer_notes' => 'setIntentionTransferNotes',
        'intention_arrangements_value' => 'setIntentionArrangementsValue',
        'intention_arrangements_notes' => 'setIntentionArrangementsNotes',
        'intention_penetration_value' => 'setIntentionPenetrationValue',
        'intention_penetration_notes' => 'setIntentionPenetrationNotes',
        'intention_services_value' => 'setIntentionServicesValue',
        'intention_services_notes' => 'setIntentionServicesNotes',
        'intention_service_level_value' => 'setIntentionServiceLevelValue',
        'intention_service_level_notes' => 'setIntentionServiceLevelNotes',
        'intention_notification_transports_value' => 'setIntentionNotificationTransportsValue',
        'intention_notification_transports_notes' => 'setIntentionNotificationTransportsNotes',
        'intention_notification_types_value' => 'setIntentionNotificationTypesValue',
        'intention_notification_types_notes' => 'setIntentionNotificationTypesNotes',
        'information_location_type_value' => 'setInformationLocationTypeValue',
        'information_location_type_notes' => 'setInformationLocationTypeNotes',
        'information_venue_value' => 'setInformationVenueValue',
        'information_venue_notes' => 'setInformationVenueNotes',
        'information_dock_value' => 'setInformationDockValue',
        'information_dock_notes' => 'setInformationDockNotes',
        'information_obstacles_value' => 'setInformationObstaclesValue',
        'information_obstacles_notes' => 'setInformationObstaclesNotes',
        'choices_transfer_value' => 'setChoicesTransferValue',
        'choices_transfer_notes' => 'setChoicesTransferNotes',
        'plan_transit_value' => 'setPlanTransitValue',
        'plan_transit_notes' => 'setPlanTransitNotes',
        'plan_transfer_value' => 'setPlanTransferValue',
        'plan_transfer_notes' => 'setPlanTransferNotes',
        'plan_arrangements_value' => 'setPlanArrangementsValue',
        'plan_arrangements_notes' => 'setPlanArrangementsNotes',
        'plan_penetration_value' => 'setPlanPenetrationValue',
        'plan_penetration_notes' => 'setPlanPenetrationNotes',
        'plan_services_value' => 'setPlanServicesValue',
        'plan_services_notes' => 'setPlanServicesNotes',
        'plan_service_level_value' => 'setPlanServiceLevelValue',
        'plan_service_level_notes' => 'setPlanServiceLevelNotes',
        'plan_notification_transports_value' => 'setPlanNotificationTransportsValue',
        'plan_notification_transports_notes' => 'setPlanNotificationTransportsNotes',
        'plan_notification_types_value' => 'setPlanNotificationTypesValue',
        'plan_notification_types_notes' => 'setPlanNotificationTypesNotes',
        'accessorials_total' => 'setAccessorialsTotal'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'contact' => 'getContact',
        'address_line1' => 'getAddressLine1',
        'address_line2' => 'getAddressLine2',
        'city' => 'getCity',
        'state' => 'getState',
        'postal_code' => 'getPostalCode',
        'country' => 'getCountry',
        'notes' => 'getNotes',
        'intention_transit_value' => 'getIntentionTransitValue',
        'intention_transit_notes' => 'getIntentionTransitNotes',
        'intention_transfer_value' => 'getIntentionTransferValue',
        'intention_transfer_notes' => 'getIntentionTransferNotes',
        'intention_arrangements_value' => 'getIntentionArrangementsValue',
        'intention_arrangements_notes' => 'getIntentionArrangementsNotes',
        'intention_penetration_value' => 'getIntentionPenetrationValue',
        'intention_penetration_notes' => 'getIntentionPenetrationNotes',
        'intention_services_value' => 'getIntentionServicesValue',
        'intention_services_notes' => 'getIntentionServicesNotes',
        'intention_service_level_value' => 'getIntentionServiceLevelValue',
        'intention_service_level_notes' => 'getIntentionServiceLevelNotes',
        'intention_notification_transports_value' => 'getIntentionNotificationTransportsValue',
        'intention_notification_transports_notes' => 'getIntentionNotificationTransportsNotes',
        'intention_notification_types_value' => 'getIntentionNotificationTypesValue',
        'intention_notification_types_notes' => 'getIntentionNotificationTypesNotes',
        'information_location_type_value' => 'getInformationLocationTypeValue',
        'information_location_type_notes' => 'getInformationLocationTypeNotes',
        'information_venue_value' => 'getInformationVenueValue',
        'information_venue_notes' => 'getInformationVenueNotes',
        'information_dock_value' => 'getInformationDockValue',
        'information_dock_notes' => 'getInformationDockNotes',
        'information_obstacles_value' => 'getInformationObstaclesValue',
        'information_obstacles_notes' => 'getInformationObstaclesNotes',
        'choices_transfer_value' => 'getChoicesTransferValue',
        'choices_transfer_notes' => 'getChoicesTransferNotes',
        'plan_transit_value' => 'getPlanTransitValue',
        'plan_transit_notes' => 'getPlanTransitNotes',
        'plan_transfer_value' => 'getPlanTransferValue',
        'plan_transfer_notes' => 'getPlanTransferNotes',
        'plan_arrangements_value' => 'getPlanArrangementsValue',
        'plan_arrangements_notes' => 'getPlanArrangementsNotes',
        'plan_penetration_value' => 'getPlanPenetrationValue',
        'plan_penetration_notes' => 'getPlanPenetrationNotes',
        'plan_services_value' => 'getPlanServicesValue',
        'plan_services_notes' => 'getPlanServicesNotes',
        'plan_service_level_value' => 'getPlanServiceLevelValue',
        'plan_service_level_notes' => 'getPlanServiceLevelNotes',
        'plan_notification_transports_value' => 'getPlanNotificationTransportsValue',
        'plan_notification_transports_notes' => 'getPlanNotificationTransportsNotes',
        'plan_notification_types_value' => 'getPlanNotificationTypesValue',
        'plan_notification_types_notes' => 'getPlanNotificationTypesNotes',
        'accessorials_total' => 'getAccessorialsTotal'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['contact'] = isset($data['contact']) ? $data['contact'] : null;
        $this->container['address_line1'] = isset($data['address_line1']) ? $data['address_line1'] : null;
        $this->container['address_line2'] = isset($data['address_line2']) ? $data['address_line2'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['postal_code'] = isset($data['postal_code']) ? $data['postal_code'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
        $this->container['intention_transit_value'] = isset($data['intention_transit_value']) ? $data['intention_transit_value'] : null;
        $this->container['intention_transit_notes'] = isset($data['intention_transit_notes']) ? $data['intention_transit_notes'] : null;
        $this->container['intention_transfer_value'] = isset($data['intention_transfer_value']) ? $data['intention_transfer_value'] : null;
        $this->container['intention_transfer_notes'] = isset($data['intention_transfer_notes']) ? $data['intention_transfer_notes'] : null;
        $this->container['intention_arrangements_value'] = isset($data['intention_arrangements_value']) ? $data['intention_arrangements_value'] : null;
        $this->container['intention_arrangements_notes'] = isset($data['intention_arrangements_notes']) ? $data['intention_arrangements_notes'] : null;
        $this->container['intention_penetration_value'] = isset($data['intention_penetration_value']) ? $data['intention_penetration_value'] : null;
        $this->container['intention_penetration_notes'] = isset($data['intention_penetration_notes']) ? $data['intention_penetration_notes'] : null;
        $this->container['intention_services_value'] = isset($data['intention_services_value']) ? $data['intention_services_value'] : null;
        $this->container['intention_services_notes'] = isset($data['intention_services_notes']) ? $data['intention_services_notes'] : null;
        $this->container['intention_service_level_value'] = isset($data['intention_service_level_value']) ? $data['intention_service_level_value'] : null;
        $this->container['intention_service_level_notes'] = isset($data['intention_service_level_notes']) ? $data['intention_service_level_notes'] : null;
        $this->container['intention_notification_transports_value'] = isset($data['intention_notification_transports_value']) ? $data['intention_notification_transports_value'] : null;
        $this->container['intention_notification_transports_notes'] = isset($data['intention_notification_transports_notes']) ? $data['intention_notification_transports_notes'] : null;
        $this->container['intention_notification_types_value'] = isset($data['intention_notification_types_value']) ? $data['intention_notification_types_value'] : null;
        $this->container['intention_notification_types_notes'] = isset($data['intention_notification_types_notes']) ? $data['intention_notification_types_notes'] : null;
        $this->container['information_location_type_value'] = isset($data['information_location_type_value']) ? $data['information_location_type_value'] : null;
        $this->container['information_location_type_notes'] = isset($data['information_location_type_notes']) ? $data['information_location_type_notes'] : null;
        $this->container['information_venue_value'] = isset($data['information_venue_value']) ? $data['information_venue_value'] : null;
        $this->container['information_venue_notes'] = isset($data['information_venue_notes']) ? $data['information_venue_notes'] : null;
        $this->container['information_dock_value'] = isset($data['information_dock_value']) ? $data['information_dock_value'] : null;
        $this->container['information_dock_notes'] = isset($data['information_dock_notes']) ? $data['information_dock_notes'] : null;
        $this->container['information_obstacles_value'] = isset($data['information_obstacles_value']) ? $data['information_obstacles_value'] : null;
        $this->container['information_obstacles_notes'] = isset($data['information_obstacles_notes']) ? $data['information_obstacles_notes'] : null;
        $this->container['choices_transfer_value'] = isset($data['choices_transfer_value']) ? $data['choices_transfer_value'] : null;
        $this->container['choices_transfer_notes'] = isset($data['choices_transfer_notes']) ? $data['choices_transfer_notes'] : null;
        $this->container['plan_transit_value'] = isset($data['plan_transit_value']) ? $data['plan_transit_value'] : null;
        $this->container['plan_transit_notes'] = isset($data['plan_transit_notes']) ? $data['plan_transit_notes'] : null;
        $this->container['plan_transfer_value'] = isset($data['plan_transfer_value']) ? $data['plan_transfer_value'] : null;
        $this->container['plan_transfer_notes'] = isset($data['plan_transfer_notes']) ? $data['plan_transfer_notes'] : null;
        $this->container['plan_arrangements_value'] = isset($data['plan_arrangements_value']) ? $data['plan_arrangements_value'] : null;
        $this->container['plan_arrangements_notes'] = isset($data['plan_arrangements_notes']) ? $data['plan_arrangements_notes'] : null;
        $this->container['plan_penetration_value'] = isset($data['plan_penetration_value']) ? $data['plan_penetration_value'] : null;
        $this->container['plan_penetration_notes'] = isset($data['plan_penetration_notes']) ? $data['plan_penetration_notes'] : null;
        $this->container['plan_services_value'] = isset($data['plan_services_value']) ? $data['plan_services_value'] : null;
        $this->container['plan_services_notes'] = isset($data['plan_services_notes']) ? $data['plan_services_notes'] : null;
        $this->container['plan_service_level_value'] = isset($data['plan_service_level_value']) ? $data['plan_service_level_value'] : null;
        $this->container['plan_service_level_notes'] = isset($data['plan_service_level_notes']) ? $data['plan_service_level_notes'] : null;
        $this->container['plan_notification_transports_value'] = isset($data['plan_notification_transports_value']) ? $data['plan_notification_transports_value'] : null;
        $this->container['plan_notification_transports_notes'] = isset($data['plan_notification_transports_notes']) ? $data['plan_notification_transports_notes'] : null;
        $this->container['plan_notification_types_value'] = isset($data['plan_notification_types_value']) ? $data['plan_notification_types_value'] : null;
        $this->container['plan_notification_types_notes'] = isset($data['plan_notification_types_notes']) ? $data['plan_notification_types_notes'] : null;
        $this->container['accessorials_total'] = isset($data['accessorials_total']) ? $data['accessorials_total'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets contact
     * @return \Gateway\Client\Model\Contact
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     * @param \Gateway\Client\Model\Contact $contact
     * @return $this
     */
    public function setContact($contact)
    {
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets address_line1
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->container['address_line1'];
    }

    /**
     * Sets address_line1
     * @param string $address_line1
     * @return $this
     */
    public function setAddressLine1($address_line1)
    {
        $this->container['address_line1'] = $address_line1;

        return $this;
    }

    /**
     * Gets address_line2
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->container['address_line2'];
    }

    /**
     * Sets address_line2
     * @param string $address_line2
     * @return $this
     */
    public function setAddressLine2($address_line2)
    {
        $this->container['address_line2'] = $address_line2;

        return $this;
    }

    /**
     * Gets city
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     * @param string $city
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     * @param string $state
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets postal_code
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     * @param string $postal_code
     * @return $this
     */
    public function setPostalCode($postal_code)
    {
        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets country
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     * @param string $country
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets notes
     * @return string
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     * @param string $notes
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets intention_transit_value
     * @return string[]
     */
    public function getIntentionTransitValue()
    {
        return $this->container['intention_transit_value'];
    }

    /**
     * Sets intention_transit_value
     * @param string[] $intention_transit_value
     * @return $this
     */
    public function setIntentionTransitValue($intention_transit_value)
    {
        $this->container['intention_transit_value'] = $intention_transit_value;

        return $this;
    }

    /**
     * Gets intention_transit_notes
     * @return string
     */
    public function getIntentionTransitNotes()
    {
        return $this->container['intention_transit_notes'];
    }

    /**
     * Sets intention_transit_notes
     * @param string $intention_transit_notes
     * @return $this
     */
    public function setIntentionTransitNotes($intention_transit_notes)
    {
        $this->container['intention_transit_notes'] = $intention_transit_notes;

        return $this;
    }

    /**
     * Gets intention_transfer_value
     * @return string[]
     */
    public function getIntentionTransferValue()
    {
        return $this->container['intention_transfer_value'];
    }

    /**
     * Sets intention_transfer_value
     * @param string[] $intention_transfer_value
     * @return $this
     */
    public function setIntentionTransferValue($intention_transfer_value)
    {
        $this->container['intention_transfer_value'] = $intention_transfer_value;

        return $this;
    }

    /**
     * Gets intention_transfer_notes
     * @return string
     */
    public function getIntentionTransferNotes()
    {
        return $this->container['intention_transfer_notes'];
    }

    /**
     * Sets intention_transfer_notes
     * @param string $intention_transfer_notes
     * @return $this
     */
    public function setIntentionTransferNotes($intention_transfer_notes)
    {
        $this->container['intention_transfer_notes'] = $intention_transfer_notes;

        return $this;
    }

    /**
     * Gets intention_arrangements_value
     * @return string[]
     */
    public function getIntentionArrangementsValue()
    {
        return $this->container['intention_arrangements_value'];
    }

    /**
     * Sets intention_arrangements_value
     * @param string[] $intention_arrangements_value
     * @return $this
     */
    public function setIntentionArrangementsValue($intention_arrangements_value)
    {
        $this->container['intention_arrangements_value'] = $intention_arrangements_value;

        return $this;
    }

    /**
     * Gets intention_arrangements_notes
     * @return string
     */
    public function getIntentionArrangementsNotes()
    {
        return $this->container['intention_arrangements_notes'];
    }

    /**
     * Sets intention_arrangements_notes
     * @param string $intention_arrangements_notes
     * @return $this
     */
    public function setIntentionArrangementsNotes($intention_arrangements_notes)
    {
        $this->container['intention_arrangements_notes'] = $intention_arrangements_notes;

        return $this;
    }

    /**
     * Gets intention_penetration_value
     * @return string[]
     */
    public function getIntentionPenetrationValue()
    {
        return $this->container['intention_penetration_value'];
    }

    /**
     * Sets intention_penetration_value
     * @param string[] $intention_penetration_value
     * @return $this
     */
    public function setIntentionPenetrationValue($intention_penetration_value)
    {
        $this->container['intention_penetration_value'] = $intention_penetration_value;

        return $this;
    }

    /**
     * Gets intention_penetration_notes
     * @return string
     */
    public function getIntentionPenetrationNotes()
    {
        return $this->container['intention_penetration_notes'];
    }

    /**
     * Sets intention_penetration_notes
     * @param string $intention_penetration_notes
     * @return $this
     */
    public function setIntentionPenetrationNotes($intention_penetration_notes)
    {
        $this->container['intention_penetration_notes'] = $intention_penetration_notes;

        return $this;
    }

    /**
     * Gets intention_services_value
     * @return string[]
     */
    public function getIntentionServicesValue()
    {
        return $this->container['intention_services_value'];
    }

    /**
     * Sets intention_services_value
     * @param string[] $intention_services_value
     * @return $this
     */
    public function setIntentionServicesValue($intention_services_value)
    {
        $this->container['intention_services_value'] = $intention_services_value;

        return $this;
    }

    /**
     * Gets intention_services_notes
     * @return string
     */
    public function getIntentionServicesNotes()
    {
        return $this->container['intention_services_notes'];
    }

    /**
     * Sets intention_services_notes
     * @param string $intention_services_notes
     * @return $this
     */
    public function setIntentionServicesNotes($intention_services_notes)
    {
        $this->container['intention_services_notes'] = $intention_services_notes;

        return $this;
    }

    /**
     * Gets intention_service_level_value
     * @return string[]
     */
    public function getIntentionServiceLevelValue()
    {
        return $this->container['intention_service_level_value'];
    }

    /**
     * Sets intention_service_level_value
     * @param string[] $intention_service_level_value
     * @return $this
     */
    public function setIntentionServiceLevelValue($intention_service_level_value)
    {
        $this->container['intention_service_level_value'] = $intention_service_level_value;

        return $this;
    }

    /**
     * Gets intention_service_level_notes
     * @return string
     */
    public function getIntentionServiceLevelNotes()
    {
        return $this->container['intention_service_level_notes'];
    }

    /**
     * Sets intention_service_level_notes
     * @param string $intention_service_level_notes
     * @return $this
     */
    public function setIntentionServiceLevelNotes($intention_service_level_notes)
    {
        $this->container['intention_service_level_notes'] = $intention_service_level_notes;

        return $this;
    }

    /**
     * Gets intention_notification_transports_value
     * @return string[]
     */
    public function getIntentionNotificationTransportsValue()
    {
        return $this->container['intention_notification_transports_value'];
    }

    /**
     * Sets intention_notification_transports_value
     * @param string[] $intention_notification_transports_value
     * @return $this
     */
    public function setIntentionNotificationTransportsValue($intention_notification_transports_value)
    {
        $this->container['intention_notification_transports_value'] = $intention_notification_transports_value;

        return $this;
    }

    /**
     * Gets intention_notification_transports_notes
     * @return string
     */
    public function getIntentionNotificationTransportsNotes()
    {
        return $this->container['intention_notification_transports_notes'];
    }

    /**
     * Sets intention_notification_transports_notes
     * @param string $intention_notification_transports_notes
     * @return $this
     */
    public function setIntentionNotificationTransportsNotes($intention_notification_transports_notes)
    {
        $this->container['intention_notification_transports_notes'] = $intention_notification_transports_notes;

        return $this;
    }

    /**
     * Gets intention_notification_types_value
     * @return string[]
     */
    public function getIntentionNotificationTypesValue()
    {
        return $this->container['intention_notification_types_value'];
    }

    /**
     * Sets intention_notification_types_value
     * @param string[] $intention_notification_types_value
     * @return $this
     */
    public function setIntentionNotificationTypesValue($intention_notification_types_value)
    {
        $this->container['intention_notification_types_value'] = $intention_notification_types_value;

        return $this;
    }

    /**
     * Gets intention_notification_types_notes
     * @return string
     */
    public function getIntentionNotificationTypesNotes()
    {
        return $this->container['intention_notification_types_notes'];
    }

    /**
     * Sets intention_notification_types_notes
     * @param string $intention_notification_types_notes
     * @return $this
     */
    public function setIntentionNotificationTypesNotes($intention_notification_types_notes)
    {
        $this->container['intention_notification_types_notes'] = $intention_notification_types_notes;

        return $this;
    }

    /**
     * Gets information_location_type_value
     * @return string[]
     */
    public function getInformationLocationTypeValue()
    {
        return $this->container['information_location_type_value'];
    }

    /**
     * Sets information_location_type_value
     * @param string[] $information_location_type_value
     * @return $this
     */
    public function setInformationLocationTypeValue($information_location_type_value)
    {
        $this->container['information_location_type_value'] = $information_location_type_value;

        return $this;
    }

    /**
     * Gets information_location_type_notes
     * @return string
     */
    public function getInformationLocationTypeNotes()
    {
        return $this->container['information_location_type_notes'];
    }

    /**
     * Sets information_location_type_notes
     * @param string $information_location_type_notes
     * @return $this
     */
    public function setInformationLocationTypeNotes($information_location_type_notes)
    {
        $this->container['information_location_type_notes'] = $information_location_type_notes;

        return $this;
    }

    /**
     * Gets information_venue_value
     * @return string[]
     */
    public function getInformationVenueValue()
    {
        return $this->container['information_venue_value'];
    }

    /**
     * Sets information_venue_value
     * @param string[] $information_venue_value
     * @return $this
     */
    public function setInformationVenueValue($information_venue_value)
    {
        $this->container['information_venue_value'] = $information_venue_value;

        return $this;
    }

    /**
     * Gets information_venue_notes
     * @return string
     */
    public function getInformationVenueNotes()
    {
        return $this->container['information_venue_notes'];
    }

    /**
     * Sets information_venue_notes
     * @param string $information_venue_notes
     * @return $this
     */
    public function setInformationVenueNotes($information_venue_notes)
    {
        $this->container['information_venue_notes'] = $information_venue_notes;

        return $this;
    }

    /**
     * Gets information_dock_value
     * @return string[]
     */
    public function getInformationDockValue()
    {
        return $this->container['information_dock_value'];
    }

    /**
     * Sets information_dock_value
     * @param string[] $information_dock_value
     * @return $this
     */
    public function setInformationDockValue($information_dock_value)
    {
        $this->container['information_dock_value'] = $information_dock_value;

        return $this;
    }

    /**
     * Gets information_dock_notes
     * @return string
     */
    public function getInformationDockNotes()
    {
        return $this->container['information_dock_notes'];
    }

    /**
     * Sets information_dock_notes
     * @param string $information_dock_notes
     * @return $this
     */
    public function setInformationDockNotes($information_dock_notes)
    {
        $this->container['information_dock_notes'] = $information_dock_notes;

        return $this;
    }

    /**
     * Gets information_obstacles_value
     * @return string[]
     */
    public function getInformationObstaclesValue()
    {
        return $this->container['information_obstacles_value'];
    }

    /**
     * Sets information_obstacles_value
     * @param string[] $information_obstacles_value
     * @return $this
     */
    public function setInformationObstaclesValue($information_obstacles_value)
    {
        $this->container['information_obstacles_value'] = $information_obstacles_value;

        return $this;
    }

    /**
     * Gets information_obstacles_notes
     * @return string
     */
    public function getInformationObstaclesNotes()
    {
        return $this->container['information_obstacles_notes'];
    }

    /**
     * Sets information_obstacles_notes
     * @param string $information_obstacles_notes
     * @return $this
     */
    public function setInformationObstaclesNotes($information_obstacles_notes)
    {
        $this->container['information_obstacles_notes'] = $information_obstacles_notes;

        return $this;
    }

    /**
     * Gets choices_transfer_value
     * @return string[]
     */
    public function getChoicesTransferValue()
    {
        return $this->container['choices_transfer_value'];
    }

    /**
     * Sets choices_transfer_value
     * @param string[] $choices_transfer_value
     * @return $this
     */
    public function setChoicesTransferValue($choices_transfer_value)
    {
        $this->container['choices_transfer_value'] = $choices_transfer_value;

        return $this;
    }

    /**
     * Gets choices_transfer_notes
     * @return string
     */
    public function getChoicesTransferNotes()
    {
        return $this->container['choices_transfer_notes'];
    }

    /**
     * Sets choices_transfer_notes
     * @param string $choices_transfer_notes
     * @return $this
     */
    public function setChoicesTransferNotes($choices_transfer_notes)
    {
        $this->container['choices_transfer_notes'] = $choices_transfer_notes;

        return $this;
    }

    /**
     * Gets plan_transit_value
     * @return string[]
     */
    public function getPlanTransitValue()
    {
        return $this->container['plan_transit_value'];
    }

    /**
     * Sets plan_transit_value
     * @param string[] $plan_transit_value
     * @return $this
     */
    public function setPlanTransitValue($plan_transit_value)
    {
        $this->container['plan_transit_value'] = $plan_transit_value;

        return $this;
    }

    /**
     * Gets plan_transit_notes
     * @return string
     */
    public function getPlanTransitNotes()
    {
        return $this->container['plan_transit_notes'];
    }

    /**
     * Sets plan_transit_notes
     * @param string $plan_transit_notes
     * @return $this
     */
    public function setPlanTransitNotes($plan_transit_notes)
    {
        $this->container['plan_transit_notes'] = $plan_transit_notes;

        return $this;
    }

    /**
     * Gets plan_transfer_value
     * @return string[]
     */
    public function getPlanTransferValue()
    {
        return $this->container['plan_transfer_value'];
    }

    /**
     * Sets plan_transfer_value
     * @param string[] $plan_transfer_value
     * @return $this
     */
    public function setPlanTransferValue($plan_transfer_value)
    {
        $this->container['plan_transfer_value'] = $plan_transfer_value;

        return $this;
    }

    /**
     * Gets plan_transfer_notes
     * @return string
     */
    public function getPlanTransferNotes()
    {
        return $this->container['plan_transfer_notes'];
    }

    /**
     * Sets plan_transfer_notes
     * @param string $plan_transfer_notes
     * @return $this
     */
    public function setPlanTransferNotes($plan_transfer_notes)
    {
        $this->container['plan_transfer_notes'] = $plan_transfer_notes;

        return $this;
    }

    /**
     * Gets plan_arrangements_value
     * @return string[]
     */
    public function getPlanArrangementsValue()
    {
        return $this->container['plan_arrangements_value'];
    }

    /**
     * Sets plan_arrangements_value
     * @param string[] $plan_arrangements_value
     * @return $this
     */
    public function setPlanArrangementsValue($plan_arrangements_value)
    {
        $this->container['plan_arrangements_value'] = $plan_arrangements_value;

        return $this;
    }

    /**
     * Gets plan_arrangements_notes
     * @return string
     */
    public function getPlanArrangementsNotes()
    {
        return $this->container['plan_arrangements_notes'];
    }

    /**
     * Sets plan_arrangements_notes
     * @param string $plan_arrangements_notes
     * @return $this
     */
    public function setPlanArrangementsNotes($plan_arrangements_notes)
    {
        $this->container['plan_arrangements_notes'] = $plan_arrangements_notes;

        return $this;
    }

    /**
     * Gets plan_penetration_value
     * @return string[]
     */
    public function getPlanPenetrationValue()
    {
        return $this->container['plan_penetration_value'];
    }

    /**
     * Sets plan_penetration_value
     * @param string[] $plan_penetration_value
     * @return $this
     */
    public function setPlanPenetrationValue($plan_penetration_value)
    {
        $this->container['plan_penetration_value'] = $plan_penetration_value;

        return $this;
    }

    /**
     * Gets plan_penetration_notes
     * @return string
     */
    public function getPlanPenetrationNotes()
    {
        return $this->container['plan_penetration_notes'];
    }

    /**
     * Sets plan_penetration_notes
     * @param string $plan_penetration_notes
     * @return $this
     */
    public function setPlanPenetrationNotes($plan_penetration_notes)
    {
        $this->container['plan_penetration_notes'] = $plan_penetration_notes;

        return $this;
    }

    /**
     * Gets plan_services_value
     * @return string[]
     */
    public function getPlanServicesValue()
    {
        return $this->container['plan_services_value'];
    }

    /**
     * Sets plan_services_value
     * @param string[] $plan_services_value
     * @return $this
     */
    public function setPlanServicesValue($plan_services_value)
    {
        $this->container['plan_services_value'] = $plan_services_value;

        return $this;
    }

    /**
     * Gets plan_services_notes
     * @return string
     */
    public function getPlanServicesNotes()
    {
        return $this->container['plan_services_notes'];
    }

    /**
     * Sets plan_services_notes
     * @param string $plan_services_notes
     * @return $this
     */
    public function setPlanServicesNotes($plan_services_notes)
    {
        $this->container['plan_services_notes'] = $plan_services_notes;

        return $this;
    }

    /**
     * Gets plan_service_level_value
     * @return string[]
     */
    public function getPlanServiceLevelValue()
    {
        return $this->container['plan_service_level_value'];
    }

    /**
     * Sets plan_service_level_value
     * @param string[] $plan_service_level_value
     * @return $this
     */
    public function setPlanServiceLevelValue($plan_service_level_value)
    {
        $this->container['plan_service_level_value'] = $plan_service_level_value;

        return $this;
    }

    /**
     * Gets plan_service_level_notes
     * @return string
     */
    public function getPlanServiceLevelNotes()
    {
        return $this->container['plan_service_level_notes'];
    }

    /**
     * Sets plan_service_level_notes
     * @param string $plan_service_level_notes
     * @return $this
     */
    public function setPlanServiceLevelNotes($plan_service_level_notes)
    {
        $this->container['plan_service_level_notes'] = $plan_service_level_notes;

        return $this;
    }

    /**
     * Gets plan_notification_transports_value
     * @return string[]
     */
    public function getPlanNotificationTransportsValue()
    {
        return $this->container['plan_notification_transports_value'];
    }

    /**
     * Sets plan_notification_transports_value
     * @param string[] $plan_notification_transports_value
     * @return $this
     */
    public function setPlanNotificationTransportsValue($plan_notification_transports_value)
    {
        $this->container['plan_notification_transports_value'] = $plan_notification_transports_value;

        return $this;
    }

    /**
     * Gets plan_notification_transports_notes
     * @return string
     */
    public function getPlanNotificationTransportsNotes()
    {
        return $this->container['plan_notification_transports_notes'];
    }

    /**
     * Sets plan_notification_transports_notes
     * @param string $plan_notification_transports_notes
     * @return $this
     */
    public function setPlanNotificationTransportsNotes($plan_notification_transports_notes)
    {
        $this->container['plan_notification_transports_notes'] = $plan_notification_transports_notes;

        return $this;
    }

    /**
     * Gets plan_notification_types_value
     * @return string[]
     */
    public function getPlanNotificationTypesValue()
    {
        return $this->container['plan_notification_types_value'];
    }

    /**
     * Sets plan_notification_types_value
     * @param string[] $plan_notification_types_value
     * @return $this
     */
    public function setPlanNotificationTypesValue($plan_notification_types_value)
    {
        $this->container['plan_notification_types_value'] = $plan_notification_types_value;

        return $this;
    }

    /**
     * Gets plan_notification_types_notes
     * @return string
     */
    public function getPlanNotificationTypesNotes()
    {
        return $this->container['plan_notification_types_notes'];
    }

    /**
     * Sets plan_notification_types_notes
     * @param string $plan_notification_types_notes
     * @return $this
     */
    public function setPlanNotificationTypesNotes($plan_notification_types_notes)
    {
        $this->container['plan_notification_types_notes'] = $plan_notification_types_notes;

        return $this;
    }

    /**
     * Gets accessorials_total
     * @return string
     */
    public function getAccessorialsTotal()
    {
        return $this->container['accessorials_total'];
    }

    /**
     * Sets accessorials_total
     * @param string $accessorials_total
     * @return $this
     */
    public function setAccessorialsTotal($accessorials_total)
    {
        $this->container['accessorials_total'] = $accessorials_total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Gateway\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Gateway\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


